pool: agents-dev

jobs:
- job:
  displayName: SonarQube
  container: maven:3.8.3-adoptopenjdk-15
  steps:
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqube-dev1'
      scannerMode: 'Other'
      extraProperties: |
        # Additional properties that will be passed to the scanner, 
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
        sonar.projectKey=WebGoatSonarQube2
  - task: Maven@4
    inputs:
      mavenPomFile: 'WebGoat/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'